language: java
jdk:
  - oraclejdk8
before_install:
  - wget https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
  - mkdir opt
  - tar -xvzf atlassian-plugin-sdk* -C opt
  - mv opt/atlassian-plugin-sdk* opt/atlassian-plugin-sdk
  - export PATH=opt/atlassian-plugin-sdk/bin:$PATH
  - atlas-version
install:
  - atlas-mvn install
script:
  - atlas-package
